development:
  adapter: postgresql
  encoding: unicode
  database: capistrano_dev
  pool: 5
  username: postgres
#  password: '27091'

test  :
  adapter: postgresql
  encoding: unicode
  database: capistrano_test
  pool: 5
  username: postgres
  password: '2709'

production:
  adapter: postgresql
  encoding: unicode
  database: capistrano_production
  pool: 5
  username: postgres
  password: '2709'